"""
Divide & Conquer Min-Max Temperature Analysis
Entry point — run this file to start the application.

Usage:
    python main.py

When prompted:
    - Enter 'data/sample_countries.csv' for real country data
    - Press Enter for random data
"""
import sys
import time

# Add src to path so all modules resolve correctly
sys.path.insert(0, 'src')

from src.utils.data_loader import load_data
from src.algorithms.iterative_min_max import find_min_max as iterative_minmax
from src.algorithms.divide_conquer_min_max import DivideConquerMinMax, print_tree
from src.visualization.animation import animate


def generate_html_report(data, labels, iter_res, dc_res, sample, root_node, filename):
    """Generate an HTML report with full results."""
    import os
    os.makedirs('output', exist_ok=True)
    html_file = 'output/weather_analysis_report.html'

    from datetime import datetime

    def tree_str(node, depth=0):
        if node is None:
            return ''
        indent = '  ' * depth
        s = f"{indent}[{node.left}..{node.right}] min={node.min:.2f} max={node.max:.2f}\n"
        s += tree_str(node.left_child, depth + 1)
        s += tree_str(node.right_child, depth + 1)
        return s

    with open(html_file, 'w', encoding='utf-8') as f:
        f.write(f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Weather Data Analysis - Min-Max Temperatures</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 20px; background: #f8f9fa; }}
        h1, h2 {{ color: #2c3e50; }}
        table {{ border-collapse: collapse; width: 100%; margin: 20px 0; background: white; }}
        th, td {{ border: 1px solid #ddd; padding: 8px; text-align: center; }}
        th {{ background: #3498db; color: white; }}
        tr:nth-child(even) {{ background: #f2f2f2; }}
        pre {{ background: #ecf0f1; padding: 10px; border-left: 4px solid #3498db; overflow-x: auto; }}
        .footer {{ margin-top: 30px; font-size: 0.8em; color: #7f8c8d; text-align: center; }}
    </style>
</head>
<body>
    <h1>Weather Data Analysis: Min-Max Temperature</h1>
    <p><strong>Dataset size:</strong> {len(data)} records</p>
    <p><strong>Analysis date:</strong> {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>
    <h2>Results on Full Dataset</h2>
    <table>
        <tr><th>Algorithm</th><th>Min (C)</th><th>Max (C)</th><th>Comparisons</th></tr>
        <tr><td>Iterative</td><td>{iter_res.min:.2f}</td><td>{iter_res.max:.2f}</td><td>{iter_res.comparisons}</td></tr>
        <tr><td>Divide &amp; Conquer</td><td>{dc_res.min:.2f}</td><td>{dc_res.max:.2f}</td><td>{dc_res.comparisons}</td></tr>
    </table>
    <h2>Recursion Tree (first {len(sample)} elements)</h2>
    <pre>{tree_str(root_node)}</pre>
    <h2>Recurrence Relation</h2>
    <p><strong>T(n) = 2T(n/2) + 2</strong> solves to <strong>3n/2 - 2</strong> comparisons.</p>
    <div class="footer">
        <p>Generated by Weather Data Analysis Tool | Dataset: {filename or 'Randomly generated'}</p>
    </div>
</body>
</html>""")
    print(f"\nHTML report saved: {html_file}")


def main():
    print("=" * 55)
    print("  Divide & Conquer Min-Max Temperature Analysis")
    print("=" * 55)

    filename = input("\nEnter CSV filename (or press Enter for random data): ").strip()
    size_input = input("Enter number of records (default 1000): ").strip()
    size = int(size_input) if size_input else 1000

    data, labels = load_data(filename if filename else None, size)
    print(f"\nUsing {len(data)} records.\n")

    # Run both algorithms
    print("--- Results on full dataset ---")
    iter_res = iterative_minmax(data)
    dc_res   = DivideConquerMinMax.find_min_max(data)
    print(f"Iterative:       {iter_res}")
    print(f"Divide&Conquer:  {dc_res}")

    min_idx = data.index(iter_res.min)
    max_idx = data.index(iter_res.max)
    print(f"\n  Coldest: {labels[min_idx]} -> {iter_res.min:.2f}C")
    print(f"  Hottest: {labels[max_idx]} -> {iter_res.max:.2f}C")

    # Recursion tree on small sample
    sample_size = min(len(data), 8)
    sample      = data[:sample_size]
    slabels     = labels[:sample_size]
    print(f"\n--- Recursion Tree (first {sample_size} elements) ---")
    root_node = DivideConquerMinMax.build_tree(sample)
    print_tree(root_node)

    # Performance data
    sizes = [500, 1000, 5000]
    iter_times, dc_times = [], []
    for n in sizes:
        td, _ = load_data(size=n)
        t0 = time.perf_counter(); iterative_minmax(td)
        iter_times.append((time.perf_counter() - t0) * 1000)
        t0 = time.perf_counter(); DivideConquerMinMax.find_min_max(td)
        dc_times.append((time.perf_counter() - t0) * 1000)

    print("\nLaunching animated GUI...")
    perf_data = {'sizes': sizes, 'iter_times': iter_times, 'dc_times': dc_times}
    animate(sample, perf_data=perf_data, labels=slabels,
            full_data=data, full_labels=labels)

    generate_html_report(data, labels, iter_res, dc_res, sample, root_node, filename)


if __name__ == '__main__':
    main()
    